"""
Generate the example city brief that ships with the repo.

    python -m scripts.generate_sample_report "Pune" --country India

Writes examples/<city>-brief.md and prints a short run summary. Whatever
RUN_MODE is set to is what you get: run it in LIVE mode to produce a real
brief from live internet research (this is the one the case study asks for),
or in MOCK mode to produce a deterministic structural example with no keys.

This is a thin wrapper around the same `workflow` the API calls — it exists
so the committed example is genuinely generated by the system rather than
written by hand.
"""
import argparse
import asyncio
import sys
from pathlib import Path

from app.config import settings
from app.graph.workflow import WORKFLOW_CONFIG, workflow
from app.models.schemas import ConfidenceTier

EXAMPLES_DIR = Path(__file__).resolve().parent.parent / "examples"


async def generate(city: str, country: str | None) -> int:
    print(f"Researching {city} in {settings.RUN_MODE} mode — this can take a few minutes.\n")

    state = await workflow.ainvoke(
        {"city": city, "country": country, "retry_count": 0}, config=WORKFLOW_CONFIG
    )

    report = state.get("report_markdown")
    if not report:
        print("The pipeline produced no report.", file=sys.stderr)
        return 1

    facts = state.get("fact_checked", [])

    def count(tier: ConfidenceTier) -> int:
        return sum(1 for f in facts if f.tier == tier)

    EXAMPLES_DIR.mkdir(parents=True, exist_ok=True)
    slug = city.lower().replace(" ", "-")
    path = EXAMPLES_DIR / f"{slug}-brief.md"
    path.write_text(report, encoding="utf-8")

    covered = state.get("covered_dimensions", [])
    print(f"Dimensions covered : {len(covered)} of {len(state.get('dimensions', []))}")
    print(f"Research passes    : {state.get('retry_count', 0) + 1}")
    print(f"Sources read       : {len(state.get('passages', []))}")
    print(f"Verified           : {count(ConfidenceTier.VERIFIED)}")
    print(f"Single source      : {count(ConfidenceTier.SINGLE_SOURCE)}")
    print(f"Conflicting        : {count(ConfidenceTier.CONFLICTING)}")
    print(f"Dropped/unsupported: {count(ConfidenceTier.UNSUPPORTED)}")
    print(f"Gaps logged        : {len(state.get('gaps', []))}")

    for warning in state.get("warnings", []):
        print(f"  warning: {warning}")

    print(f"\nWrote {path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a sample city brief.")
    parser.add_argument("city", help="City to research, e.g. Pune")
    parser.add_argument("--country", default=None, help="Optional country, improves search precision")
    args = parser.parse_args()
    return asyncio.run(generate(args.city, args.country))


if __name__ == "__main__":
    sys.exit(main())
